title: "Mickael ASSELINE"
subtitle: "Portfolio of a tech enthusiast !"
social_links:
  - name: "GitHub"
    icon: "https://img.papamica.com/stickers/github.png"
    url: "https://github.com/PAPAMICA"
  - name: "LinkedIn"
    icon: "https://img.papamica.com/stickers/linkedin.png"
    url: "https://www.linkedin.com/in/mickael-asseline/"
  - name: "Resume"
    icon: "https://img.papamica.com/stickers/website.png"
    url: "https://mickaelasseline.com"
  - name: "X"
    icon: "https://img.papamica.com/stickers/X.png"
    url: "https://x.com/PAPAMICA__"